name: loftup-cuda12
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - torchaudio=2.5.1
  - pytorch-cuda=12.1
  - ffmpeg
  - numpy
  - scikit-learn
  - matplotlib
  - opencv
  - pip:
      - absl-py
      - accelerate
      - cityscapesscripts
      - einops
      - ftfy
      - huggingface-hub
      - hydra-core
      - ipython
      - jinja2
      - kornia
      - kornia-rs
      - lightning-utilities
      - omegaconf
      - open-clip-torch
      - peft
      - pillow
      - propcache
      - protobuf
      - pycocotools
      - pyquaternion
      - pytorch-lightning
      - requests
      - safetensors
      - schedulefree
      - scipy
      - tensorboard
      - timm
      - tokenizers
      - tqdm
      - transformers
