name: loftup-cuda11
channels:
  - xformers
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - opencv
  - pytorch=1.13.1
  - torchvision=0.14.1
  - pytorch-cuda=11.6
  - xformers
  - faiss-gpu
  - ipykernel
  - jupyter
  - ffmpeg
  - pip:
      - absl-py
      - accelerate
      - addict
      - aiohttp
      - aliyun-python-sdk-core
      - aliyun-python-sdk-kms
      - antlr4-python3-runtime
      - clip
      - colorama
      - contourpy
      - crcmod
      - cryptography
      - einops
      - filelock
      - fonttools
      - fsspec
      - ftfy
      - grpcio
      - h5py
      - huggingface-hub
      - hydra-core
      - imageio
      - ipdb
      - jinja2
      - joblib
      - kiwisolver
      - kornia
      - kornia-rs
      - lightning-utilities
      - markdown
      - markdown-it-py
      - matplotlib-inline
      - mdurl
      - mmcv-full
      - model-index
      - networkx
      - omegaconf
      - open-clip-torch
      - opendatalab
      - openmim
      - openxlab
      - ordered-set
      - oss2
      - peft
      - pillow
      - protobuf
      - psutil
      - pycocotools
      - pycryptodome
      - pyparsing
      - pytorch-lightning
      - pyyaml
      - regex
      - requests
      - rich
      - safetensors
      - scikit-image
      - scikit-learn
      - stack-data
      - tabulate
      - tensorboard
      - timm
      - tokenizers
      - torch-tb-profiler
      - torchmetrics
      - tqdm
      - transformers
      - triton
      - werkzeug
      - yapf