-
    type: radio_lang
    args:
        image_insize: [848, 448]
        radio_type: c-radio_v3-b
        adaptor_type: siglip2

- 
    type: pca
    args:
        fp: physics_atv_visual_mapping/pca/radio_v3b_siglip2.pt