-
    type: elevation_filter
    args:
        input_layer: min_elevation
        cnt_layer: num_points

        height_low_thresh: -3.0 #cells this far below their neighbors are not terrain
        height_high_thresh: 0.5 #cells this far above their neighbors are not terrain

        kernel_params:
            kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

            kernel_radius: 2. #kernel radius in m
            kernel_sharpness: 5. #sharpness of (Gaussian) kernel

            # kernel_radius: 0.25 #kernel radius in m
            # kernel_sharpness: 0.5 #sharpness of (Gaussian) kernel

-
    type: terrain_inflation
    args:
        input_layer: min_elevation_filtered
        mask_layer: min_elevation_filtered_mask

        thresh: 0.05 #at least this frac of neighboring cells in the kernel must be observed

        kernel_params:
            kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

            kernel_radius: 5. #kernel radius in m
            kernel_sharpness: 2. #sharpness of (Gaussian) kernel

            # kernel_radius: 0.5 #kernel radius in m
            # kernel_sharpness: 1.0 #sharpness of (Gaussian) kernel

- 
    type: mrf_terrain_estimation
    args: 
        input_layer: min_elevation_filtered_inflated
        mask_layer: min_elevation_filtered_inflated_mask

        itrs: 5   #num updates
        alpha: 10. #weight on the measurement update
        beta: 1.  #weight on the neighbor update
        lr: 0.05   #learning rate

        kernel_params:
            kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

            kernel_radius: 1. #kernel radius in m
            kernel_sharpness: 2. #sharpness of (Gaussian) kernel

            # kernel_radius: 0.5
            # kernel_sharpness: 1.0

- 
    type: slope
    args:
        input_layer: terrain
        mask_layer: min_elevation_filtered_inflated_mask
        radius: 0.25
        max_slope: 2.0
        kernel_type: scharr

-
    type: normals_sobel
    args:
        slope_x_layer: slope_x
        slope_y_layer: slope_y
        mask_layer: min_elevation_filtered_inflated_mask

-
    type: bev_terrain_diff
    args:
        terrain_layer: terrain
        max_elevation_layer: max_elevation
        overhang: 2.0

-
    type: sdf
    args:
        mask_layer: num_points
        thresh: 0.01
        dilation: true