image:
    image_topic: /front_camera/image_raw
    camera_info_topic: /front_camera/camera_info
    image_compressed: False

pointcloud:
    topic: /synced_pointcloud

odometry:
    topic: /odom # frame_id /odom

gridmap:
    topic: local_gridmap

intrinsics:

    K: [407.86023253, 0.0, 533.30109486, 0.0, 407.86605705, 278.69939958, 0.0, 0.0, 1.0]
    P: [407.86023253, 0.0, 533.30109486, 0.0, 407.86605705, 278.69939958, 0.0, 0.0, 1.0]


extrinsics:
    p: [0, 0, 0]
    q: [0.5, -0.5, 0.5, 0.5]
image_processing:
    -
        type: dino
        args:
            dino_type: dinov2_vitb14
            dino_layer: 10
            # image_insize: [686, 364] #this should be the size of the input images
            image_insize: [728, 420]
            desc_facet: value
#            desc_facet: token

    -
        type: vlad
        args:
            n_clusters: 8
            cache_dir: /earthrovers_ros1_ws/src/physics_atv_visual_mapping/data/dino_clusters/8_wheelchair

localmapping:
    layer_key: VLAD
    ema: 1 #higher->use recent more
    metadata:

    #    origin: [-8., -8.]
    #    length_x: 16.
    #    length_y: 16.
    #    resolution: 0.05

       origin: [-20., -20.]
       length_x: 40.
       length_y: 40.
       resolution: 0.125

device: cuda
#viz: True
viz: False
