# voxel
voxel_localmapping:
    mapper_type: voxel
    layer_key: dino
    ema: 0.5 #higher->use recent more
    n_features: 16
    metadata:
        origin: [-60., -60., -60.]
        length: [120., 120., 120.]
        resolution: [0.25, 0.25, 0.25]

device: cuda