models_dir: /phoenix/cmu_sara_perception_models #necessary to include this for non-ROS offline proc
# models_dir: /home/tartandriver/tartandriver_ws/models

image:
    image_topic: sensors/multisense_front/aux/image_rect_color/camera_info
    camera_info_topic: sensors/multisense_front/aux/image_rect_color
    image_compressed: False

pointcloud:
   topic: registered_scan

odometry:
    topic: integrated_to_init

gridmap:
    topic: local_gridmap

#the base link of the vehicle (e.g. base_link, vehicle, etc.)
vehicle_frame: vehicle 

#camera intrinsics
intrinsics:
    K: [1064.3520, 0., 732.8348, 0., 1064.3520, 581.5662, 0., 0., 1]
    P: [1064.3520, 0., 732.8348, 0., 1064.3520, 581.5662, 0., 0., 1]

#transform from the vehicle link to the camera link
extrinsics:
    p: [0.353, 1.025, -0.627]
    q: [-0.509, 0.512, -0.492, -0.485] #xyzw

image_processing:
    # -
    #     type: radio
    #     args:
    #         radio_type: radio_v2.5-b # radio_v2 e-radio_v2
    #         image_insize: [672, 496]  # Original Image Size must be divisible by 16

    # - 
    #     type: pca
    #     args:
    #         fp: physics_atv_visual_mapping/data/dino_clusters/8_clusters_364x686_

    -
        type: dino
        args:
            dino_type: dinov2_vitb14
            dino_layer: 10
            image_insize: [686, 364] #this should be the size of the input images
            desc_facet: value
    -
        type: vlad
        args:
            n_clusters: 8
            cache_dir: /phoenix/src/perception/cmu_sara_perception/physics_atv_visual_mapping/data/dino_clusters/8_clusters_364x686_            

# voxel
localmapping:
    mapper_type: voxel
    layer_key: dino # dino
    ema: 0.5 #higher->use recent more
    n_features: 8
    metadata: #if too slow, can reduce length/height or slightly decrease resolution
        origin: [-25., -25., -10.]
        length: [50., 50., 20.]
        resolution: [0.1999, 0.1999, 0.1999]

terrain_estimation:
    -
        type: elevation_stats
        args: {}

    -
        type: elevation_filter
        args:
            input_layer: min_elevation
            cnt_layer: num_voxels

            height_low_thresh: -3.0 #cells this far below their neighbors are not terrain
            height_high_thresh: 0.5 #cells this far above their neighbors are not terrain

            kernel_params:
                kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

                kernel_radius: 0.25 #kernel radius in m
                kernel_sharpness: 0.5 #sharpness of (Gaussian) kernel

    -
        type: terrain_inflation
        args:
            input_layer: min_elevation_filtered
            mask_layer: min_elevation_filtered_mask

            kernel_params:
                kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

                kernel_radius: 0.5 #kernel radius in m
                kernel_sharpness: 1.0 #sharpness of (Gaussian) kernel

    - 
        type: mrf_terrain_estimation
        args: 
            input_layer: min_elevation_filtered_inflated
            mask_layer: min_elevation_filtered_inflated_mask

            itrs: 1   #num updates
            alpha: 5. #weight on the measurement update
            beta: 10.  #weight on the neighbor update
            lr: 0.05   #learning rate

            kernel_params:
                kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

                kernel_radius: 0.5
                kernel_sharpness: 1.0

    - 
        type: slope
        args:
            input_layer: terrain
            mask_layer: min_elevation_filtered_inflated_mask

    -
        type: terrain_diff
        args:
            terrain_layer: terrain
            max_elevation_layer: max_elevation
            max_elevation_mask_layer: num_voxels
            overhang: 1.0
    -
        type: terrain_aware_bev_feature_splat
        args:
            output_key: dino
            terrain_layer: terrain
            terrain_mask_layer: min_elevation_filtered_inflated_mask
            overhang: 1.0

device: cuda
viz: False
