image:
    image_topic: /multisense/left/image_rect_color
    camera_info_topic: /multisense/left/camera_info
    image_compressed: False

pointcloud:
    topic: /velodyne_1/velodyne_points
    # topic: /full_cloud
  #  topic: /coloroze_pcl_node/colorized_pcl

odometry:
    topic: /integrated_to_init

gridmap:
    topic: local_gridmap

intrinsics:
    K: [455.7750, 0., 497.1180, 0., 456.3191, 251.8580, 0., 0., 1.]
    P: [477.6049499511719, 0.0, 499.5,  0.0, 477.6049499511719, 252.0,  0.0, 0.0, 1.0]

extrinsics:
   # p: [0.0, 0.0, -0.1274]
   # q: [-0.549, 0.554, -0.445, -0.440] #xyzw

    # p: [0.0, 0.4, -0.3]
    # q: [0.569, -0.549, 0.416, 0.450] #xyzw

    #NEW BEST
    # p: [-0.10772, 0.07414, -0.15637]
    # q: [0.55860, -0.54800, 0.42820, 0.45200] #xyzw

    # p: [-0.10772, 0.07414, -0.15637]
    # q: [0.56017, -0.54567, 0.43487, 0.44647] #xyzw

    #NEW from Jeric
    # p: [0.14397, -0.10793, -0.27834]
    # q: [0.56175, -0.54742, 0.44230, 0.43490] #xyzw

    p: [0.17265, -0.15227, 0.05708]
    # q: [0.55940, -0.54718, 0.44603, 0.43442] #xyzw
    q: [0.55940, -0.54718, 0.44603, 0.43442] #xyzw
    # q: [0.55486, -0.55226, 0.44196, 0.43796]

    # p: [0.10883, 0.26500, 0.20678]
    # q: [-0.55162, 0.43980, -0.43711, 0.55787]

image_processing:
    -
        type: radio
        args:
            image_insize: [512, 512] #this should be the size of the input images
    -
        type: pca
        args:
            fp: /home/physics_atv/physics_atv_ws/src/perception/physics_atv_visual_mapping/data/pca/radio.pt

localmapping:
    layer_key: radio
    ema: 0.1 #higher->use recent more
    metadata:
        origin: [-40., -40.]
        length_x: 80.
        length_y: 80.
        resolution: 0.5

       # origin: [-20., -20.]
       # length_x: 40.
       # length_y: 40.
       # resolution: 0.1

device: cuda
#viz: True
viz: False
