image:
    image_topic: /multisense/left/image_rect_color
    camera_info_topic: /multisense/left/camera_info
    image_compressed: False

pointcloud:
    topic: /full_cloud
    frame: vehicle #comment this line out if your pointcloud frame is already a child of your odom frame. we set this of own internal frame conventions.

odometry:
    topic: /integrated_to_init

gridmap:
    topic: local_gridmap

intrinsics:
    K: [455.7750, 0., 497.1180, 0., 456.3191, 251.8580, 0., 0., 1.]
    P: [477.6049499511719, 0.0, 499.5,  0.0, 477.6049499511719, 252.0,  0.0, 0.0, 1.0]

extrinsics:
    p: [0.17265, -0.15227, 0.05708]
    q: [0.55940, -0.54718, 0.44603, 0.43442] #xyzw


image_processing:
    -
        type: identity
        args: {}

localmapping:
    layer_key: VLAD
    ema: 0.15 #higher->use recent more
    metadata:
        # origin: [-40., -40.]
        # length_x: 80.
        # length_y: 80.
        # resolution: 0.5

       origin: [-25., -25.]
       length_x: 50.
       length_y: 50.
       resolution: 0.1999

       # origin: [-20., -20.]
       # length_x: 40.
       # length_y: 40.
       # resolution: 0.1999

       # origin: [-20., -20.]
       # length_x: 40.
       # length_y: 40.
       # resolution: 0.125

device: cuda
#viz: True
viz: False
