models_dir: /home/tartandriver/tartandriver_ws/models #necessary to include this for non-ROS offline proc

image_processing: !include /home/tartandriver/tartandriver_ws/src/perception/physics_atv_visual_mapping/config/image_processing/radiov3_siglip2_pca.yaml

localmapping: !include /home/tartandriver/tartandriver_ws/src/perception/physics_atv_visual_mapping/config/localmapping/bev.yaml

terrain_estimation: !include /home/tartandriver/tartandriver_ws/src/perception/physics_atv_visual_mapping/config/terrain_estimation/bev_to_bev.yaml

device: cuda
viz: True
