models_dir: /home/tartandriver/tartandriver_ws/models #necessary to include this for non-ROS offline proc

image:
    image_topic: /thermal_left/image
    camera_info_topic: /thermal_left/camera_info
    image_compressed: False
    folder: thermal_left

pointcloud:
   topic: /superodometry/velodyne_cloud_registered
   folder: super_odometry_pc

odometry:
    topic: /superodometry/integrated_to_init
    folder: odom

gridmap:
    topic: local_gridmap
    folder: local_gridmap

#the base link of the vehicle (e.g. base_link, vehicle, etc.)
vehicle_frame: vehicle 

#camera intrinsics
intrinsics:
    K: [412.42744452, 0.0, 313.38643993,0.0, 412.60673097, 249.37501763, 0.0, 0.0, 1.0]
    P: [412.42744452, 0.0, 313.38643993,0.0, 412.60673097, 249.37501763, 0.0, 0.0, 1.0]

#transform from the vehicle link to the camera link
extrinsics:
    p: [ 0.19265, -0.15227,  0.05708]
    q: [ 0.5574714, -0.54525728,  0.44844936,  0.43682184] #xyzw

image_processing:
    -
        type: thermal
        args: 
            process: minmax #thermal 16->8 processing: minmax / hist
            enhance: False #apply enhancement to 8bit
            rectify: True #perform rectify
            distortion: [-0.367732796157476, 0.12110213142717571, -0.0006255396681117811, 0.00041510869260370575]
            colormap: inferno


# voxel
localmapping:
    mapper_type: voxel
    layer_key: dino
    ema: 0.5 #higher->use recent more
    n_features: 3
    metadata:
        origin: [-60., -60., -30.]
        length: [120., 120., 60.]
        resolution: [0.4, 0.4, 0.4]

pca_nfeats: 64 #reduce output feats to this dim
#pca_nfeats: 128 #reduce output feats to this dim

pcl_mindist: 3.0
pcl_maxdist: 50.0

terrain_estimation:
    -
        type: elevation_stats
        args: {}

    -
        type: elevation_filter
        args:
            input_layer: min_elevation
            cnt_layer: num_voxels

            height_low_thresh: -3.0 #cells this far below their neighbors are not terrain
            height_high_thresh: 0.5 #cells this far above their neighbors are not terrain

            kernel_params:
                kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

                kernel_radius: 2. #kernel radius in m
                kernel_sharpness: 5. #sharpness of (Gaussian) kernel

    -
        type: terrain_inflation
        args:
            input_layer: min_elevation_filtered
            mask_layer: min_elevation_filtered_mask

            kernel_params:
                kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

                kernel_radius: 5. #kernel radius in m
                kernel_sharpness: 10. #sharpness of (Gaussian) kernel

    - 
        type: mrf_terrain_estimation
        args: 
            input_layer: min_elevation_filtered_inflated
            mask_layer: min_elevation_filtered_inflated_mask

            itrs: 1   #num updates
            alpha: 5. #weight on the measurement update
            beta: 10.  #weight on the neighbor update
            lr: 0.05   #learning rate

            kernel_params:
                kernel_type: gaussian #one of {gaussian/box} the kernel type to use for inflation

                kernel_radius: 5. #kernel radius in m
                kernel_sharpness: 10. #sharpness of (Gaussian) kernel

                # kernel_radius: 0.5
                # kernel_sharpness: 1.0

    - 
        type: slope
        args:
            input_layer: terrain
            mask_layer: min_elevation_filtered_inflated_mask

    -
        type: terrain_diff
        args:
            terrain_layer: terrain
            max_elevation_layer: max_elevation
            max_elevation_mask_layer: num_voxels
            overhang: 2.0
    -
        type: terrain_aware_bev_feature_splat
        args:
            output_key: dino
            terrain_layer: terrain
            terrain_mask_layer: min_elevation_filtered_inflated_mask
            overhang: 1.7

device: cuda
viz: True
