models_dir: /home/tartandriver/tartandriver_ws/models

image:
    folder: image_left_color

pointcloud:
    folder: pcl

odometry:
    folder: odom

image_processing:
    -
        type: dino
        args:
            dino_type: dinov2_vitb14
            dino_layer: 10
            image_insize: [686, 364] #this should be the size of the input images
            desc_facet: value

pca_nfeats: 64 #reduce output feats to this dim
#pca_nfeats: 128 #reduce output feats to this dim

pcl_mindist: 3.0
pcl_maxdist: 50.0

extrinsics:
    p: [0.17265, -0.15227, 0.05708]
    q: [0.55940, -0.54718, 0.44603, 0.43442] #xyzw

#this is for the original image size (we will auto-adjust to reflect image_insize)
intrinsics:
    K: [477.6049499511719, 0.0, 499.5,  0.0, 477.6049499511719, 252.0,  0.0, 0.0, 1.0]

device: cuda
